name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@6fede2f0550d71291c0accf2834b216e69a2d67a
        with:
          version: master

      - name: Compilation to multiple targets
        run: |
          zig build
          zig build -Drelease

          zig build -Dtarget=x86_64-linux -Dcpu=baseline
          zig build -Dtarget=aarch64-linux -Dcpu=baseline+aes+crypto
          zig build -Dtarget=x86_64-windows -Dcpu=baseline
          zig build -Dtarget=aarch64-windows -Dcpu=baseline+aes+crypto
          zig build -Dtarget=x86_64-macos -Dcpu=baseline
          zig build -Dtarget=aarch64-macos -Dcpu=apple_m2

          zig build -Dtarget=x86_64-linux -Dcpu=znver4
          zig build -Dtarget=aarch64-linux -Dcpu=ampere1a+aes+crypto
          zig build -Dtarget=x86_64-windows -Dcpu=znver4
          zig build -Dtarget=aarch64-windows -Dcpu=ampere1a+aes+crypto
          zig build -Dtarget=x86_64-macos -Dcpu=znver4
          zig build -Dtarget=aarch64-macos -Dcpu=apple_m2
          zig build -Dtarget=wasm32-wasi

          rm -fr zig-cache zig-out
