name: Clang-CL

on:
  push:
    branches: [ "main", "cl" ]
  pull_request:
    branches: [ "main", "cl" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: ilammy/msvc-dev-cmd@v1    

    - name: Predefined macros
      env:
        CC: clang-cl
      run: |
        touch empty.c
        $(CC) -d1PP empty.c | grep -E "^\s*#define" | sort
        
    - name: Configure CMake
      env:
        CC: clang-cl
        CMAKE_GENERATOR: Ninja
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build            
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
