name: version check

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Version check
        run: |
            grep -E 'const version =' build.zig | grep -E '"${{  github.ref_name }}"' || exit 78
            echo "Zig build version check passed."
            grep -E 'COMPATIBILITY AnyNewerVersion' CMakeLists.txt | grep -E ' ${{  github.ref_name }} ' || exit 78
            echo "CMake version check passed."
